### PR TITLE
Bump coiled version to 0.0.33

### PR DESCRIPTION
**Pull request by FabioRosado**
Hello,

I was testing the notebook examples on our site and got an `ImportError: Coiled now requires coiled>=0.0.33 but you are using coiled version 0.0.30`, this PR bumps the version of coiled 😄

### CODE REVIEW

**Comment by FabioRosado** [comment]
I've tried to fix the yaml error on the GitHub actions as well. This last commit didn't seem to trigger a GitHub action error, so maybe that works? 🤔  I've used the [workflow syntax for GitHub actions](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet) documentation to try and figure out why we were getting an error on line 19.

It seems that we can only use a few regex characters; the updated regex pattern should still do what we want. Let me know if you want me to change anything on this PR 😄 👍

**Review by jrbourbeau — COMMENTED** [review]
Thanks for catching that out CI jobs for auto-updating `coiled` wasn't working and manually updating to the latest release! Would you mind removing the regex update for now and I'll open a separate PR (and will ping you) to ensure the GitHub actions job runs?

**Review by jrbourbeau — APPROVED** [review]
Thanks @FabioRosado!

**Comment by FabioRosado** [comment]
Awesome thanks 😄

**Pull request merged**
