### PR TITLE
Break environments into environment.yaml files so they can be reused more easily.

### PR DESCRIPTION
**Pull request by ian-r-rose**
Over in `coiled/integration-tests` I'm trying to test these -- it would be useful to have separate `environment.yml` files to more easily drive them. Any objections @jrbourbeau?

### CODE REVIEW

**Review by jrbourbeau — COMMENTED** [review]
No objection from me! Just to double check, do we need to update our GitHub action which automatically updates package versions?

**Comment by ian-r-rose** [comment]
Ooh, good catch @jrbourbeau. I had thought not since it is just a regex, but we are in fact scoping it to [`create-notebook.py`](https://github.com/coiled/notebooks/blob/2bb3f0d1d40eac0f77fc978d19450e43f86d93d0/.github/workflows/ci-bump-version.yml#L43)

**Comment by ian-r-rose** [comment]
okay, should be fixed

**Comment by jrbourbeau** [comment]
Sounds good, I'll trust you on those regular expressions : )

**Comment by ian-r-rose** [comment]
Well, maybe don't trust me on them, but trust that I'll fix them if/when they break :)

**Pull request merged**
