### PR TITLE
Updates for new nyc taxi data

### PR DESCRIPTION
**Pull request by scharlottej13**
Update `read_csv` to `read_parquet` for NYC taxi dataset (https://www1.nyc.gov/site/tlc/about/tlc-trip-record-data.page)

### CODE REVIEW

**Comment by scharlottej13** [comment]
cc @jrbourbeau @ian-r-rose since it looks like you two wrote a lot of these

**Comment by ian-r-rose** [comment]
Thanks @scharlottej13, these look good to me.

I'm curious what our plan for this repo is? From my perspective it was effectively archived after we dropped notebook support last fall.

**Comment by scharlottej13** [comment]
> I'm curious what our plan for this repo is? From my perspective it was effectively archived after we dropped notebook support last fall.

Thanks @ian-r-rose! Ah, I was wondering why these were in a separate repo. The coiled docs still point to these notebooks from https://docs.coiled.io/user_guide/examples.html, but maybe it makes sense to move these over with the rest of the docs.

**Comment by scharlottej13** [comment]
@ian-r-rose I'm going to merge this in for now, I've opened up a [gitlab issue](https://gitlab.com/coiled/cloud/-/issues/4967) for discussing whether to move these examples

**Comment by ian-r-rose** [comment]
Sounds good, thanks @scharlottej13

**Pull request merged**
